# Generated by Django 4.2.6 on 2023-10-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Augmentation',
            fields=[
                ('augmentation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('display', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'augmentations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('level', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('fill_level', models.FloatField(blank=True, null=True)),
                ('recommended_fill_level', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsIngredient',
            fields=[
                ('pair_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('ingredient_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'items_ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersItem',
            fields=[
                ('pair_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'orders_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersItemsAugmentation',
            fields=[
                ('augmentation_pair_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pair_id', models.IntegerField()),
                ('augmentation_id', models.IntegerField()),
            ],
            options={
                'db_table': 'orders_items_augmentations',
                'managed': False,
            },
        ),
    ]
